name: Static analysis

on: pull_request

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  tests:
    name: Static analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version:
          - "3.11"
        os: ["ubuntu-22.04"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system requirements
        run: sudo apt update && sudo apt install -y libxmlsec1-dev

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.15"
          enable-cache: true
          cache-dependency-glob: |
            requirements/edx/development.txt

      - name: Install python dependencies
        run: make dev-requirements

      - name: Static code analysis
        run: make check-types
