name: Lint Python Imports

on:
  pull_request:
  push:
    branches:
      - master

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  lint-imports:
    name: Lint Python Imports
    runs-on: ubuntu-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system requirements
        run: sudo apt update && sudo apt install -y libxmlsec1-dev

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.15"
          enable-cache: true
          cache-dependency-glob: |
            requirements/edx/development.txt

      - name: Install python dependencies
        run: make dev-requirements

      # As long there are sub-projects[1] in edx-platform, we analyze each
      # project separately here, in order to make import-linting errors easier
      # to pinpoint.
      #
      #  [1] https://openedx.atlassian.net/browse/BOM-2579

      - name: Analyze imports (repo root)
        run: make lint-imports
